spring:
  profiles:
    active: dev
  ## 国际化配置,
  ## 1. messages，以配置的方式使用
  ## 2. CustomResourceBundle，以类的方式使用
  messages:
    basename: messages, pers.jyzh.springboot.web.i18n.bundles.CustomResourceBundle

tij:
  config:
    k1: v1
    k2:
      - v21
      - v22
      - v33
